/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Apropos': RouteRecordInfo<
      '/Apropos',
      '/Apropos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Calendrier': RouteRecordInfo<
      '/Calendrier',
      '/Calendrier',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Candidature': RouteRecordInfo<
      '/Candidature',
      '/Candidature',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Contact': RouteRecordInfo<
      '/Contact',
      '/Contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Equipes/': RouteRecordInfo<
      '/Equipes/',
      '/Equipes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Equipes/[id]': RouteRecordInfo<
      '/Equipes/[id]',
      '/Equipes/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/Joueurs/': RouteRecordInfo<
      '/Joueurs/',
      '/Joueurs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Joueurs/[id]': RouteRecordInfo<
      '/Joueurs/[id]',
      '/Joueurs/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/MentionsLegales': RouteRecordInfo<
      '/MentionsLegales',
      '/MentionsLegales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/PolitiqueConfidentialite': RouteRecordInfo<
      '/PolitiqueConfidentialite',
      '/PolitiqueConfidentialite',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Stream': RouteRecordInfo<
      '/Stream',
      '/Stream',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/Apropos.vue': {
      routes:
        | '/Apropos'
      views:
        | never
    }
    'src/pages/Calendrier.vue': {
      routes:
        | '/Calendrier'
      views:
        | never
    }
    'src/pages/Candidature.vue': {
      routes:
        | '/Candidature'
      views:
        | never
    }
    'src/pages/Contact.vue': {
      routes:
        | '/Contact'
      views:
        | never
    }
    'src/pages/Equipes/index.vue': {
      routes:
        | '/Equipes/'
      views:
        | never
    }
    'src/pages/Equipes/[id].vue': {
      routes:
        | '/Equipes/[id]'
      views:
        | never
    }
    'src/pages/Joueurs/index.vue': {
      routes:
        | '/Joueurs/'
      views:
        | never
    }
    'src/pages/Joueurs/[id].vue': {
      routes:
        | '/Joueurs/[id]'
      views:
        | never
    }
    'src/pages/MentionsLegales.vue': {
      routes:
        | '/MentionsLegales'
      views:
        | never
    }
    'src/pages/PolitiqueConfidentialite.vue': {
      routes:
        | '/PolitiqueConfidentialite'
      views:
        | never
    }
    'src/pages/Stream.vue': {
      routes:
        | '/Stream'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
